TASK-1 Added initial configuration app
dobernike/my_finances pull request #1
Opened 2020-02-02 18:49 UTC by dobernike

2020-02-03 05:30 UTC, kkamik requested changes

2020-02-03 05:30 UTC, kkamik commented on src/components/ErrorBoundary.tsx
> +        // Catch errors in any components below and re-render with error message
поубирай комментарии плз

2020-02-03 05:30 UTC, kkamik commented on src/components/ErrorBoundary.tsx
> +    state: State = { error: null, errorInfo: null };
и null из дефолтных тожн лучше убрать. Или undefined, или прост не задавай, оно уже есть в типе

2020-02-03 05:30 UTC, kkamik commented on src/components/ErrorBoundary.tsx
> +    error: object;
я бы описал детальнее :)

2020-02-03 05:30 UTC, kkamik commented on src/components/ErrorBoundary.tsx
> +                    <details style={{ whiteSpace: 'pre-wrap' }}>
стили в css файл и убрать br

2020-02-03 05:30 UTC, kkamik commented on src/store/reducers/rootReducer.ts
> +export default () => ({});
это потом изменится, ведь так?

2020-02-03 05:32 UTC, dobernike commented on src/store/reducers/rootReducer.ts
> +export default () => ({});
Да заглушка для настройки)

2020-02-03 05:35 UTC, dobernike commented on src/components/ErrorBoundary.tsx
> +                    <details style={{ whiteSpace: 'pre-wrap' }}>
Просто копипаст с офф примера реакта, ок поправлю его
Стоит ли делать файл стилей, если используется 1 строка стилей на весь файл? Раньше всегда делал отдельно, но на работе, говорят, что лучше не делать, ради одного стиля) Я всегда за вариант, чтобы стили были в стилях

2020-02-03 17:07 UTC, dobernike commented on src/components/ErrorBoundary.tsx
> +        // Catch errors in any components below and re-render with error message
Убрал

2020-02-03 17:10 UTC, dobernike commented on src/components/ErrorBoundary.tsx
> +    state: State = { error: null, errorInfo: null };
Сделал undef

2020-02-03 17:13 UTC, dobernike commented on src/components/ErrorBoundary.tsx
> +    error: object;
Сделал

2020-02-03 19:12 UTC, dobernike commented on src/components/ErrorBoundary.tsx
> +                    <details style={{ whiteSpace: 'pre-wrap' }}>
Сделал

2020-02-05 07:01 UTC, kkamik commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +        if (this.state.errorInfo) {
1. можно пойти от обратного, сделать (!this.state.errorInfo) { return children} тем самым уменьшив вложенность.
2. this.state.error используется 2+ раз -> можно задестрактить
3. this.state.errorInfo используется 2+ раз -> можно задестрактить.

2020-02-05 21:33 UTC, dobernike commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +        if (this.state.errorInfo) {
Сделал

2020-02-11 08:35 UTC, kkamik commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +const styles = require('./ErrorBoundary.css');
давай импорты починим сразу?)

2020-02-11 08:36 UTC, kkamik commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +type TError = Error;
а в чем смысл делать TError и тп? Почему сразу нельзя сделать
type State = {
   error?: Error;
....
}

2020-02-11 09:29 UTC, dobernike commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +type TError = Error;
Ниже я кидаю TError в тип componentDidCatch, а так дублировать придется

2020-02-11 09:30 UTC, dobernike commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +const styles = require('./ErrorBoundary.css');
А у вас починен он?)

2020-02-11 09:35 UTC, kkamik commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +const styles = require('./ErrorBoundary.css');
ну да

2020-02-11 09:36 UTC, kkamik commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +type TError = Error;
все равно не понимаю зачем ты так делаешь. Ну в componentDidCatch укажешь ты типы из реакта, че такого?

2020-02-11 10:04 UTC, dobernike commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +type TError = Error;
Чтобы, если у меня поменяются типы в 1 месте, я бы не менял в другом. Ну да, в данном случаи согласен, изменю

2020-02-11 10:04 UTC, dobernike commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +const styles = require('./ErrorBoundary.css');
Не в курсе как?) Помню долго чекал, но решия тогда не нашел

2020-02-11 18:44 UTC, merged